# 指定当前运行 docker-Compose的版本号
version: "3"
# 指定网路使用
networks:
  mysite:
services:
  wwww:
    build:
      myapp
    networks:
      - mysite
    ports:
      - "12345:5000"
    depends_on:
      - db
    container_name: web
  mynginx:
    build:
      nginx
    networks:
      - mysite
    depends_on:
      - wwww
    ports:
      - "80:80"
    container_name: nginx
  db:
    image: "hub.c.163.com/library/mysql:latest"
    networks:
      - mysite
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root2
      MYSQL_PASSWORD: 123456
    volumes:
      - $PWD/data/:/var/lib/mysql
    ports:
      - "3308:3306"
    container_name: db

